language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
script:
  - ./build.sh --quiet verify
notifications:
  webhooks:
    secure: "V+ynhkZnRWn9VemSgBKI6KB5WxSE/SuoIKFnBQFb/1O0r15aac4/VyzuRdTK8V29OxdI1vK0J3UET2c2v2Q2IusFc4rCHGcRIobjHq+YW8944betuYfHkpVgniHofaGLgJH8gdlZv4elDdVHWKndYIGTaBU8+dO8ktp+9BFGYhs="
  on_success: always
  on_failure: always
  on_start: always
